version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_eventmeetup
    environment:
      POSTGRES_DB: eventmeetup
      POSTGRES_USER: eventmeetup
      POSTGRES_PASSWORD: eventmeetup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
